**Imporing Libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Importing Dataset**

In [ ]:
dataset=pd.read_csv('Data.csv')
mof=dataset.iloc[:, :-1].values
dv=dataset.iloc[:,-1].values

In [ ]:
print("Matrix of features:\n",mof,"\n")

Matrix of features:
 [[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]] 



In [ ]:
print("Dependent variables:\n",dv)

Dependent variables:
 [463.26 444.37 488.56 ... 429.57 435.74 453.28]


**Splitting dataset into training and test set**

In [ ]:
from sklearn.model_selection import train_test_split
mof_train,mof_test,dv_train,dv_test=train_test_split(mof,dv,test_size=0.2,random_state=0)

In [ ]:
print("Training set:\n")
print("Matrix of feature:\n",mof_train,"\n")
print("Dependent Variables:\n",dv_train)

Training set:

Matrix of feature:
 [[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]] 

Dependent Variables:
 [473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [ ]:
print("Test set:\n")
print("Matrix of feature:\n",mof_test,"\n")
print("Dependent Variables:\n",dv_test)

Test set:

Matrix of feature:
 [[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]] 

Dependent Variables:
 [431.23 460.01 461.14 ... 473.26 438.   463.28]


**Training Model**

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(mof_train,dv_train)

**Testing model**

In [ ]:
dv_prediction=lr.predict(mof_test)
np.set_printoptions(precision=2)
print(np.concatenate((dv_prediction.reshape(len(dv_prediction),1),dv_test.reshape(len(dv_test),1)),1))

**Evaluating Model**

In [ ]:
from sklearn.metrics import r2_score
r2_score(dv_test,dv_prediction)

0.9325315554761303